Iter5
kbondar17/metrics pull request #2
Opened 2024-01-16 16:34 UTC by kbondar17

2024-01-21 22:10 UTC, Nikscorp requested changes
Оставил замечания в комментариях к PR

2024-01-21 22:10 UTC, Nikscorp commented on cmd/agent/logs/agent_logs.log
> +Agent: 2024/01/10 20:07:15 Logger initialized
логи ни в коем случае не надо комитить в репозиторий. Удали файл и добавь его в gitignore

2024-01-21 22:10 UTC, Nikscorp commented on cmd/agent/main.go
> +func getConfig() (int, int, string) {
это следует вынести в отдельный пакет и возвращать не (int, int, string), а структуру

2024-01-21 22:10 UTC, Nikscorp commented on cmd/agent/main.go
> +	reportInterval, pollInterval, serverAddress := getConfig()
давай сразу уберем отовсюду пустые строки в начале функции — выглядит очень неаккуратно

2024-01-21 22:10 UTC, Nikscorp commented on cmd/agent/main.go
> +	"metrics/internal/utils"
никогда не стоит называть пакет utils/common/stuff и т.д. Пакет должен нести чету зону ответственности и называться в соответствии со своим функционалом

2024-01-21 22:10 UTC, Nikscorp commented on cmd/agent/main.go
> +	fmt.Println("Config::", reportInterval, pollInterval, serverAddress)
дава уберем это, если нужно что-то залогировать — логируй логгером

2024-01-21 22:10 UTC, Nikscorp commented on cmd/agent/main.go
> +
лишняя пустая строка в конце функции

2024-01-21 22:10 UTC, Nikscorp commented on cmd/server/main.go
> +func getConfig() string {
аналогично я бы сразу вынес этот в отдельный пакет и возвращал структуру

2024-01-21 22:10 UTC, Nikscorp commented on go.mod
> +go 1.21.2
я бы убрал минорную версию из `go.mod` и оставил просто 1.21

2024-01-21 22:10 UTC, Nikscorp commented on internal/agent/collector.go
> +var PollCount int
почему это глобальная переменная (еще и публичная), а не приватное поле структуры?

2024-01-21 22:10 UTC, Nikscorp commented on internal/agent/collector.go
> +func parseMetric(metricName string, value reflect.Value) string {
использование reflect-а здесь — это костыль. Из типа метрики явно не следует, что она Counter или Gauge.

Лучше явно перечислить используемые метрики из memstats

2024-01-21 22:10 UTC, Nikscorp commented on internal/agent/config.go
> +	PollInterval   int
почему поля публичные?

2024-01-21 22:10 UTC, Nikscorp commented on internal/agent/config.go
> +	ServerAddress  url.URL
а почему тут и ниже url.URL, а не обычный string?

2024-01-21 22:10 UTC, Nikscorp commented on internal/agent/connectors.go
> +var userClient UserClient
зачем нужна глобальная переменная?

2024-01-21 22:10 UTC, Nikscorp commented on internal/agent/connectors.go
> +		err := fmt.Errorf("error while sending data  %v", errs)
%v -> %w.

В сообщении об ошибке не пишут слово error, и так понятно, что это ошибка

2024-01-21 22:10 UTC, Nikscorp commented on internal/agent/connectors.go
> +		fmt.Println("Error while sending data  ", err)
есть же логгер.

Странно и логировать ошибку и возвращать ее. Обычно логируют ее в одном месте — как можно выше

2024-01-21 22:10 UTC, Nikscorp commented on internal/agent/connectors.go
> +func (uc UserClient) SendMultipleLogsAsync(data map[string]string, metricType m.MetricType) {
разве в задании такое (конкурентное) требовалось?

В такой реализации есть ряд проблем:
- Acquire a token выполняется в горутине, что может привести к переполнению стека при большом размере data. Обычно его заполняют до создания горутины
- Если значений в мапе будет больше 50 и каждый вызов будет завершаться с ошибкой — все просто повиснет на записи в errCh
- вообще непонятно зачем тебе errCh, если все что ты делаешь — логирование, почему бы не логировать сразу

То, что ты пытаешься реализовать уже реализовано в errgroup. Я бы не стал велосипедить.
А главное — не стал бы выполнять то, чего не требуется в задании, это ж потом проверять и исправлять еще. Лучше пока это удалить и написать пока обычную отправку по одному запросу в цикле

2024-01-21 22:10 UTC, Nikscorp commented on internal/agent/connectors.go
> +	// wg.Wait()
?

2024-01-21 22:10 UTC, Nikscorp commented on internal/agent/collector.go
> +		if int(time.Since(start).Seconds()) >= coll.config.ReportInterval {
сомнительный дизайн. Получается если PollInterval по каким-то причинам будет больше ReportInterval-а. Отправлять мы будем раз в PollInterval, а не в Report.

Я бы просто переписал на один цикл с select-ом и [тикерами](https://pkg.go.dev/time#NewTicker)

2024-01-21 22:10 UTC, Nikscorp commented on internal/database/memory.go
> +		log.Fatal("unknown metric type", metrciType, name)
Fatal сразу сделает os.Exit и программа завершится, его тут явно не стоит использовать

2024-01-21 22:10 UTC, Nikscorp commented on internal/database/memory.go
> +	log.Println("updating metric", name, metrciType, value)
У тебя где-то используется свой logger, а где-то log. Нужно оставить что-то одно. (Советую log), тк теория для написания корректного блоггера будет дана уже в следующем спринте

2024-01-21 22:10 UTC, Nikscorp commented on internal/database/memory.go
> +	switch metrciType {
metric

2024-01-21 22:10 UTC, Nikscorp commented on internal/database/metrics.go
> +type Storager interface {
в go интерфейсы приятно описывать в пакете, который использует структуру, а не объявляет ее

2024-01-21 22:10 UTC, Nikscorp commented on internal/utils/custom_errors.go
> +	AlreadyExists     AppError = "already exists"
для того, что тут написано есть errors.New().

Прошу почитать про нейминг и про то как пользоваться ошибками здесь https://github.com/uber-go/guide/blob/master/style.md#errors

2024-01-21 22:10 UTC, Nikscorp commented on internal/database/redis.go
> +package database
прошу пока удалить это и все то, что явно не требовалось делать в задании:
- redis
- concurrency
- свой логгер

2024-01-21 22:10 UTC, Nikscorp commented on internal/models/metrics.go
> +	Name  string  `json:"name" validate:"required"`
в чем назначения тега validate

2024-01-21 22:10 UTC, Nikscorp commented on internal/routers/metrics_test.go
> +	"gopkg.in/go-playground/assert.v1"
предполагался github.com/stretchr/testify/assert ?

2024-01-21 22:10 UTC, Nikscorp commented on cmd/agent/main.go
> +	"metrics/internal/utils"
https://go.dev/blog/package-names

2024-01-21 22:10 UTC, Nikscorp commented on internal/agent/worker.go
> +func (w Worker) Start() {
Start обычно подразумевает деблокирующий режим работы. Это скорее Run

2024-01-21 22:10 UTC, Nikscorp commented on internal/app/init.go
> +	storage := db.NewStorage(ctx)
зачем передавать контекст в конструктор?

2024-01-21 22:10 UTC, Nikscorp commented on internal/database/memory.go
> +	ctx       context.Context
зачем тут контекст?

2024-01-25 07:48 UTC, Nikscorp requested changes
Привет!

Многие замечания с прошлого раза не исправлены. Оставил несколько новых.
Новые исправления не будут приниматься без комментариев к PR что и справлено / что нет. К текущему PR комментариев от тебя не было (или ты их не запаблишил).

Сама работа очень сильно переусложнена — кода слишком много, будет здорово если ты его почистишь от лишней вложенности и абстракций.

2024-01-25 07:48 UTC, Nikscorp commented on go.mod
> +go 1.21.2
не исправлено

2024-01-25 07:48 UTC, Nikscorp commented on internal/agent/collector.go
> +func parseMetric(metricName string, value reflect.Value) string {
не исправлено

2024-01-25 07:48 UTC, Nikscorp commented on cmd/agent/main.go
> +
все еще много лишних пустых строк в начале функции — выглядит неаккуратно

2024-01-25 07:48 UTC, Nikscorp commented on internal/agent/collector.go
> +func (coll *Collector) _CollectMetrics() m.MetricSendContainer {
если есть неиспользуемый код — его надо удалять. Восстановить что-то если что ты сможешь из гита, но это ты вредил захочешь восстанавливать

2024-01-25 07:48 UTC, Nikscorp commented on internal/agent/config.go
> +func NewAgentConfig(pollInterval int, reportInterval int, serverAddress string) AgentConfig {
эта получается должна быть приватной

2024-01-25 07:48 UTC, Nikscorp commented on internal/agent/config.go
> +	serverAddress  url.URL
зачем тут url.URL, еще один не исправленный комментарий с предыдущего раза

2024-01-25 07:48 UTC, Nikscorp commented on internal/agent/connectors.go
> +	_, _, errs := uc.httpClient.Post(url).End()
почему errs, а не err?

2024-01-25 07:48 UTC, Nikscorp commented on internal/app/config.go
> +func NewAppConfig(host string) *AppConfig {
это теперь тоже может быть приватным

2024-01-25 07:48 UTC, Nikscorp commented on internal/app/config.go
> +	Server ServerConfig
зачем здесь лишняя вложенность?

2024-01-27 07:23 UTC, kbondar17 commented on internal/agent/connectors.go
> +	_, _, errs := uc.httpClient.Post(url).End()
потому что httpClient.Post(url) возвращает []error

2024-01-27 07:33 UTC, kbondar17 commented on internal/agent/collector.go
> +func parseMetric(metricName string, value reflect.Value) string {
не очень понял твой коммент( в данном случае все метрики Gauge, просто runtime.ReadMemStats может отдать int, а может float. это мы и обрабатываем

2024-01-29 06:58 UTC, Nikscorp approved these changes
ряд замечаний все равно не исправлен :/

Но ок, работу принимаю.

2024-01-30 18:28 UTC, merged